version: "3.9"
services:
  test_db_server:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - "database_store:/var/lib/postgresql/data"

volumes:
  database_store: